package com.practice;

public class CatchExceptionHandling {
    public static void main(String[] args) {

//        Generate another Exception in catch block
        try{
            int a = 100/0;
        }catch (Exception e){
            int b = 200/0;
        }
        System.out.println("Rest of the code");















//        Handle Exception in catch block

//        int a = 100;
//        int b = 0;
//        int data ;
//        try{
//            data = a/b;
//        }catch (Exception e){
//            System.out.println("Data : " + a/(b+2));
//        }
    }
}
